### ISSUE TITLE
Sample weight in the objective function?

### ISSUE THREAD

**Issue by haochen-rye** [caiqi/sample-weighting-network#1]
Hi Qi,
First, congratulations to your CVPR 2020 and thanks for your code.
About the sample weight regularization in the objective function, there seems to be a mismatch between the code and your paper. In your paper, you only regularize the sample weight once, and before the torch.exp, i.e., m_cls. But in the code, you regularize them twice, one before the torch.exp and one after, i.e., m_cls and torch.exp(m_cls).
https://github.com/caiqi/sample-weighting-network/blob/04382be7fdf83fdbc83c1606c20bd4a8b6f60880/mmdet/models/detectors/two_stage_swn_faster.py#L291
 https://github.com/caiqi/sample-weighting-network/blob/04382be7fdf83fdbc83c1606c20bd4a8b6f60880/mmdet/models/detectors/two_stage_swn_faster.py#L300
Wondering which is true, the paper or the code?
Looking forward to your reply, thanks in advance!

**Comment by caiqi** [comment]
Hi @Cassie94 , 
Thanks for your interest in our paper.  For updating in this line: https://github.com/caiqi/sample-weighting-network/blob/04382be7fdf83fdbc83c1606c20bd4a8b6f60880/mmdet/models/detectors/two_stage_swn_faster.py#L300

It will not contribute to losses since it is filtered in this line: 

https://github.com/caiqi/sample-weighting-network/blob/04382be7fdf83fdbc83c1606c20bd4a8b6f60880/mmdet/apis/train.py#L31

It is only used for logging the values of real weights. You can also find the same parsing in old version of mmdetection: 

https://github.com/open-mmlab/mmdetection/blob/bc94b21257a787ddb5c29337d8a3965cd742cf33/mmdet/apis/train.py#L28.
